# Kafka properties
spring.kafka.bootstrap-servers=kafka-0:9091,kafka-1:9091,kafka-2:9091
# set path to schema registry for our Avro-serializer (take internal port of schema-registry from docker-compose file)
spring.kafka.consumer.properties.schema.registry.url=http://schema-registry:8081