# Core application configuration
spring.application.name=krev-service
server.port=8086

# Kafka Properties
spring.kafka.bootstrap-servers=localhost:29092,localhost:29093,localhost:29094
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.group-id=krevService
spring.kafka.consumer.auto-offset-reset=latest
# set path to schema registry for our Avro-serializer (take external port of schema-registry from docker-compose file)
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8087
# to use generated record-classes for deserialization (otherwise serializer will return GenericRecord, not our Record classes that extends SpecificRecord)
spring.kafka.consumer.properties.specific.avro.reader=true

# for Utilization metrics (tomcat_threads_busy_threads, tomcat_threads_current_threads, tomcat_threads_config_max_threads)
management.metrics.enable.tomcat=true
server.tomcat.mbeanregistry.enabled=true

logging.pattern.level: "%5p [${spring.application.name}]"