{
 "title": "JVM (Micrometer) krev multi",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-10m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=~\"$application\"},instance)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"},id)"
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pools",
    "query": "label_values(jvm_buffer_memory_used_bytes{application=\"$application\", instance=\"$instance\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{application=~\"$application\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{application=\"$application\",instance=\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (application, instance) (\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      application=~\"$application\"\r\n    }[30s]\r\n  )\r\n)",
     "legendFormat": "HTTP"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (application, instance) (rate(http_server_requests_seconds_count{application=~\"$application\", status=~\"5..\"}[5m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (application) (\r\n  rate(\r\n    http_server_requests_seconds_sum{\r\n      application=~\"$application\",\r\n      status!~\"5..\"\r\n    }[5m]\r\n  )\r\n)\r\n/\r\nsum by (application) (\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      application=~\"$application\",\r\n      status!~\"5..\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max by (application) (http_server_requests_seconds_max{application=~\"$application\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threads_busy_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "TOMCAT - BSY"
    },
    {
     "expr": "tomcat_threads_current_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "TOMCAT - CUR"
    },
    {
     "expr": "tomcat_threads_config_max_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "TOMCAT - MAX"
    },
    {
     "expr": "jetty_threads_busy{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "JETTY - BSY"
    },
    {
     "expr": "jetty_threads_current{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "JETTY - CUR"
    },
    {
     "expr": "jetty_threads_config_max{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "JETTY - MAX"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=~\"$application\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Heap Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=~\"$application\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=~\"$application\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Off-Heap: Direct Memory ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_buffer_memory_used_bytes{application=~\"$application\", id=\"direct\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_buffer_memory_committed_bytes{application=~\"$application\", id=\"direct\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_buffer_memory_max_bytes{application=~\"$application\", id=\"direct\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap: Metaspace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", area=\"nonheap\", id=\"Metaspace\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\", area=\"nonheap\", id=\"Metaspace\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=~\"$application\", area=\"nonheap\", id=\"Metaspace\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap: Code Cache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (\r\n  jvm_memory_used_bytes{\r\n    application=~\"$application\",\r\n    area=\"nonheap\",\r\n    id=~\"CodeHeap.*\"\r\n  }\r\n)",
     "legendFormat": "used"
    },
    {
     "expr": "sum (\r\n  jvm_memory_committed_bytes{\r\n    application=~\"$application\",\r\n    area=\"nonheap\",\r\n    id=~\"CodeHeap.*\"\r\n  }\r\n)",
     "legendFormat": "committed"
    },
    {
     "expr": "sum (\r\n  jvm_memory_max_bytes{\r\n    application=~\"$application\",\r\n    area=\"nonheap\",\r\n    id=~\"CodeHeap.*\"\r\n  }\r\n)",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap: Compressed Class Space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{application=~\"$application\", area=\"nonheap\", id=\"Compressed Class Space\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{application=~\"$application\", area=\"nonheap\", id=\"Compressed Class Space\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{application=~\"$application\", area=\"nonheap\", id=\"Compressed Class Space\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "system_cpu_usage{application=~\"$application\"}",
     "legendFormat": "system_{{application}}"
    },
    {
     "expr": "process_cpu_usage{application=~\"$application\", instance=\"$instance\"}",
     "legendFormat": "process_{{application}}"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{application=~\"$application\", instance=\"$instance\"}[15m])",
     "legendFormat": "process-15m_{{application}}"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "system_load_average_1m{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "system-1m_{{application}}"
    },
    {
     "expr": "system_cpu_count{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "cpus_{{application}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "live_{{application}}"
    },
    {
     "expr": "jvm_threads_daemon_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "daemon_{{application}}"
    },
    {
     "expr": "jvm_threads_peak_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "peak_{{application}}"
    },
    {
     "expr": "process_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "process_{{application}}"
    }
   ]
  },
  {
   "title": "Thread States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "jvm_threads_states_threads{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "{{state}}_{{application}}"
    }
   ]
  },
  {
   "title": "GC Pressure",
   "type": "timeseries",
   "description": "The percent of time spent on Garbage Collection over all CPUs assigned to the JVM process.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{application=~\"$application\", instance=~\"$instance\"}[1m])) by (application, instance) / on(application, instance) system_cpu_count",
     "legendFormat": "CPU time spent on GC_{{application}}"
    }
   ]
  },
  {
   "title": "Log Events",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "increase(logback_events_total{application=~\"$application\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{level}}_{{application}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "process_files_open_files{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "open_{{application}}"
    },
    {
     "expr": "process_files_max_files{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "max_{{application}}"
    }
   ]
  },
  { "title": "JVM Memory Pools (Heap)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 }, "repeat": "persistence_counts" },
  {
   "title": "$jvm_memory_pool_heap",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 43 },
   "repeat": "jvm_memory_pool_heap",
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=~\"$application\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=~\"$application\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=~\"$application\", instance=~\"$instance\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "$jvm_memory_pool_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 50 },
   "repeat": "jvm_memory_pool_nonheap",
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{application=~\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_memory_committed_bytes{application=~\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "commited"
    },
    {
     "expr": "jvm_memory_max_bytes{application=~\"$application\", instance=\"$instance\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Collections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{application=~\"$application\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{action}} ({{cause}}) {{application}}"
    }
   ]
  },
  {
   "title": "Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{application=~\"$application\", instance=~\"$instance\"}[5m])/rate(jvm_gc_pause_seconds_count{application=~\"$application\", instance=~\"$instance\"}[5m])",
     "legendFormat": "avg {{action}} ({{cause}}) {{application}}"
    },
    {
     "expr": "jvm_gc_pause_seconds_max{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "max {{action}} ({{cause}}) {{application}}"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{application=~\"$application\", instance=~\"$instance\"}[5m])",
     "legendFormat": "allocated {{application}}"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{application=~\"$application\", instance=~\"$instance\"}[5m])",
     "legendFormat": "promoted {{application}}"
    }
   ]
  },
  { "title": "Classloading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{application=~\"$application\", instance=~\"$instance\"}",
     "legendFormat": "loaded_{{application}}"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{application=~\"$application\",instance=~\"$instance\"}[5m])",
     "legendFormat": "delta-1m_{{application}}"
    }
   ]
  },
  { "title": "Buffer Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "$jvm_buffer_pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 71 },
   "repeat": "jvm_buffer_pool",
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{application=~\"$application\", instance=~\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "used"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{application=~\"$application\", instance=~\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "capacity"
    },
    {
     "expr": "jvm_buffer_count_buffers{application=~\"$application\", instance=~\"$instance\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "buffers"
    }
   ]
  },
  { "title": "Hikari", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "JDBC: hikaricp connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{application=~\"$application\"})",
     "legendFormat": "active"
    },
    {
     "expr": "sum(hikaricp_connections_idle{application=~\"$application\"})",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(hikaricp_connections_pending{application=~\"$application\"})",
     "legendFormat": "pending"
    }
   ]
  }
 ]
}