# set 8080 port for all services in docker
server.port=8080
# best practice is to use separate port for actuator, but not server.port (8080)
management.server.port=9001

# Postgres properties
spring.datasource.url=jdbc:postgresql://users-postgres:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver