# set 8080 port for all services in docker
server.port=8080

# Postgres properties
spring.datasource.url=jdbc:postgresql://users-postgres:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver