# Core application configuration
spring.application.name=user-service
server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/users_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

grpc.server.port=9090
# optionally
grpc.server.keep-alive-time=30s
grpc.server.keep-alive-timeout=5s
grpc.server.permit-keep-alive-time=30s
#

# metrics (publish endpoint)
management.endpoints.web.exposure.include=health,info,prometheus,metrics
# provide access to published endpoint
management.endpoint.prometheus.access=read-only
# label to filter in Prometheus
management.metrics.tags.application=${spring.application.name}
# adds 'latency' metric for HTTP requests (NOTE: this is not necessary - it is included into Springboot)
management.metrics.web.server.auto-time-requests=true

logging.pattern.level: "%5p [${spring.application.name}]"