# Core application configuration
spring.application.name=order-service
server.port=8080

# Kafka properties
spring.kafka.bootstrap-servers=localhost:29092,localhost:29093,localhost:29094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
# set path to schema registry for our Avro-serializer (take external port of schema-registry from docker-compose file)
spring.kafka.producer.properties.schema.registry.url=http://localhost:8087

# ADD PRODUCER IDEMPOTENCY
# 0   - at-most once
# 1   - at-least once
# all - at-least once, all is MANDATORY for idempotency!
spring.kafka.producer.acks=all
# based on ProducerId + ProducerEpoch (is incremented when producer is re-created) + sequenceNumber (number of message sent by this producer)
# if true => sets transactional.id - broker assigns unique ProducerId + ProducerEpoch to the producer
spring.kafka.producer.properties.enable.idempotence=true
# how many times producer sends message without getting ack. has to be > 0
spring.kafka.producer.retries=2147483647
# max amount of messages that producer can send before getting ack regarding some of these messages. needs to be <= 5
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

# metrics (publish endpoint)
management.endpoints.web.exposure.include=health,info,prometheus,metrics
# provide access to published endpoint
management.endpoint.prometheus.access=read-only
# label to filter in Prometheus
management.metrics.tags.application=${spring.application.name}
# adds 'latency' metric for HTTP requests (NOTE: this is not necessary - it is included into Springboot)
management.metrics.web.server.auto-time-requests=true
# for p95 etc (metric http_server_requests_seconds_bucket)
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# for Utilization metrics (tomcat_threads_busy_threads, tomcat_threads_current_threads, tomcat_threads_config_max_threads)
management.metrics.enable.tomcat=true
server.tomcat.mbeanregistry.enabled=true
# max amount of worker-threads
server.tomcat.threads.max=20
# min amount of worker-threads (always ready => when burst traffic happens Tomcat will not create a lot of threads)
server.tomcat.threads.min-spare=10
# TCP connections
server.tomcat.max-connections=200

spring.threads.virtual.enabled=true

### to use OpenTelemetry and jaeger to see traces in distributed system
# turn on Spring Boot 3 Micrometer Tracing (NOTE: usual value for production 0.1 .. 0.01)
management.tracing.sampling.probability=1
management.otlp.tracing.endpoint=http://otel-collector:4318/v1/traces
# to save trace_id and span_id
logging.pattern.level: "%5p [${spring.application.name:},traceId=%X{trace_id:-},spanId=%X{span_id:-}]"