# Core application configuration
spring.application.name=order-service
server.port=8080

# Kafka properties
spring.kafka.bootstrap-servers=localhost:29092,localhost:29093,localhost:29094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# ADD PRODUCER IDEMPOTENCY
# 0   - at-most once
# 1   - at-least once
# all - at-least once, all is MANDATORY for idempotency!
spring.kafka.producer.acks=all
# based on ProducerId + ProducerEpoch (is incremented when producer is re-created) + sequenceNumber (number of message sent by this producer)
# if true => sets transactional.id - broker assigns unique ProducerId + ProducerEpoch to the producer
spring.kafka.producer.properties.enable.idempotence=true
# how many times producer sends message without getting ack. has to be > 0
spring.kafka.producer.retries=2147483647
# max amount of messages that producer can send before getting ack regarding some of these messages. needs to be <= 5
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

logging.pattern.level: "%5p [${spring.application.name}]"