# set 8080 port for all services in docker
server.port=8080
# best practice is to use separate port for actuator, but not server.port (8080)
management.server.port=9001

# Kafka properties
spring.kafka.bootstrap-servers=kafka-0:9091,kafka-1:9091,kafka-2:9091
# set path to schema registry for our Avro-serializer (take internal port of schema-registry from docker-compose file)
spring.kafka.producer.properties.schema.registry.url=http://schema-registry:8081