# Core application configuration
spring.application.name=inventory-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Kafka properties
spring.kafka.bootstrap-servers=localhost:29092,localhost:29093,localhost:29094
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# handle errors of deserialization
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
# set deserializer that will work when ErrorHandlingDeserializer does not catch error of serialization
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.group-id=inventoryService
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.properties.spring.json.trusted.packages=io.mitochondria.order.event

# ADD PRODUCER IDEMPOTENCY
# 0   - at-most once
# 1   - at-least once
# all - at-least once, all is MANDATORY for idempotency!
spring.kafka.producer.acks=all
# based on ProducerId + ProducerEpoch (is incremented when producer is re-created) + sequenceNumber (number of message sent by this producer)
# if true => sets transactional.id - broker assigns unique ProducerId + ProducerEpoch to the producer
# example from logs:
# 2026-04-16T14:40:25.884Z " INFO [inventory-service]" 1 --- [inventory-service] [vice-producer-1] o.a.k.c.p.internals.TransactionManager   : [Producer clientId=inventory-service-producer-1] ProducerId set to 12000 with epoch 0
spring.kafka.producer.properties.enable.idempotence=true
# how many times producer sends message without getting ack. has to be > 0
spring.kafka.producer.retries=2147483647
# max amount of messages that producer can send before getting ack regarding some of these messages. needs to be <= 5
spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

# CONFIGURE COMMIT FOR OFFSET
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.listener.ack-mode=record


logging.pattern.level: "%5p [${spring.application.name}]"