# Postgres properties
spring.datasource.url=jdbc:postgresql://inventory-postgres:5432/inventory_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Kafka properties
spring.kafka.bootstrap-servers=kafka-0:9091,kafka-1:9091,kafka-2:9091