apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy # requests go through Grafana-server (no CORS-problems)
    url: http://prometheus:9090 # internal container address
    isDefault: true # this datasource is default datasource for all panels