# Core application configuration
spring.application.name=analytics-service
server.port=8083

# Kafka Properties
spring.kafka.bootstrap-servers=localhost:29092,localhost:29093,localhost:29094
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.consumer.group-id=analyticsService
spring.kafka.consumer.auto-offset-reset=latest
# set path to schema registry for our Avro-serializer (take external port of schema-registry from docker-compose file)
spring.kafka.consumer.properties.schema.registry.url=http://localhost:8087
# to use generated record-classes for deserialization (otherwise serializer will return GenericRecord, not our Record classes that extends SpecificRecord)
spring.kafka.consumer.properties.specific.avro.reader=true

# metrics (publish endpoint)
management.endpoints.web.exposure.include=health,info,prometheus,metrics
# provide access to published endpoint
management.endpoint.prometheus.access=read-only
# label to filter in Prometheus
management.metrics.tags.application=${spring.application.name}
# adds 'latency' metric for HTTP requests (NOTE: this is not necessary - it is included into Springboot)
management.metrics.web.server.auto-time-requests=true

# for Utilization metrics (tomcat_threads_busy_threads, tomcat_threads_current_threads, tomcat_threads_config_max_threads)
management.metrics.enable.tomcat=true
server.tomcat.mbeanregistry.enabled=true

# since Tomcat is used only as HTTP server to send metrics to Prometheus, set very low values to save RAM
# max amount of worker-threads
server.tomcat.threads.max=4
# min amount of worker-threads (always ready => when burst traffic happens Tomcat will not create a lot of threads)
server.tomcat.threads.min-spare=1
# TCP connections
server.tomcat.max-connections=16

logging.pattern.level: "%5p [${spring.application.name}]"